http:
  routers:
    dsm:
      rule: Host(`dsm.lan`)
      service: dsm
      entrypoints: 
        - web
      middlewares:
        - url-regex
        - https-redirect
    dsm_mn:
      rule: Host(`dsm.domain.com`)
      service: dsm
      entrypoints: 
        - websecure
      tls: true
      tls:
        certResolver: le


  services:
    dsm:
      loadBalancer:
        servers:
        - url: http://192.168.1.200:5000
        passhostheader: true

        
      
       
