http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
    url-regex:
      redirectRegex:
        regex: "^^https?://(.*).lan/?"
        replacement: "https://${1}.marcnijman.nl"
        permanent: true

    add-admin:
      addPrefix:
        prefix: /admin
