http:
  routers:
    nodered:
      rule: Host(`nodered.lan`)
      service: nodered
      entrypoints: 
        - web
      middlewares:
        - url-regex
        - https-redirect
    nodered_mn:
      rule: Host(`nodered.domain.com`)
      service: nodered
      entrypoints: 
        - websecure
      tls: true
      tls:
        certResolver: le


  services:
    nodered:
      loadBalancer:
        servers:
        - url: http://192.168.1.180:1880
        passhostheader: true

        
      
       
